### ISSUE TITLE
add commit to json,bugs

### ISSUE THREAD

**Issue by xiaolu6t** [facebook-csharp-sdk/simple-json#74]
{
  //Current UrlPrefix
  "urlPrefix": "/App",
  //Current Module CookiePrefix
  "cookiePrefix": "App_",
  //Current Module SessionPrefix
  "sessionPrefix": "App_",
}
SimpleJson.DeserializeObject(json);//bugs here!

**Comment by prabirshrestha** [comment]
@xiaolu6t did you mean comment? If so we have no plans to support comment since it is not part of json spec.

**Comment by prabirshrestha** [comment]
no plans to add this as it is not part of the spec
